godmod/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from godmod import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('mods/', include('mod.urls')),
    path('game/', include('mod.urls')),

    #path('user/', include('user.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mod/urls.py
from django.urls import path
from .views import *

app_name = 'modif'

urlpatterns = [
    path('', AllMods.as_view(), name='all_mods'),
    path('add_mod/<slug>', add_mod, name='add_mod'),
    path('add_modversion/<slug>', add_modversion, name='add_modversion'),
    path('mod/<slug>/', ModDetails.as_view(), name='get_mod'),
    path('chose_game/', chose_game, name='chose_game'),
    path('<game_slug>/categories/', ModCategoriesForGame.as_view(), name='categories'),
    path('<category_slug>/', ModsByCategory.as_view(), name='mods_by_category'),

]

mod/models.py
from django.db import models
from django.urls import reverse



class Game(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True)
    description = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='GameImages/%Y/%m/%d')
    date = models.DateField()
    genre = models.CharField(max_length=30)
    team = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('modif:categories', kwargs={'game_slug': self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        pass


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('modif:mods_by_category', kwargs={'category_slug': self.slug})

    class Meta:
        verbose_name_plural = 'Categories'


class Mod(models.Model):
    name = models.CharField(max_length=30, unique=True, )
    slug = models.SlugField(max_length=30, unique=True)
    image = models.ImageField(null=True, blank=True, upload_to='ModMainImages/%Y/%m/%d')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=False)
    author = models.CharField(max_length=30)
    tag = models.ManyToManyField(Tag, blank=True)
    likes = models.IntegerField(default=0, editable=False)
    description = models.CharField(max_length=255)

    #published = models.BooleanField()
    #text = models.TextField()


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('modif:get_mod', kwargs={'slug': self.slug})

    class Meta:
        pass


class ModVersion(models.Model):
    mod = models.ForeignKey(Mod, on_delete=models.CASCADE)
    # slug = models.SlugField(max_length=30, unique=True)
    version = models.CharField(max_length=10, default='1.0', )
    files = models.FileField(null=True, blank=True, upload_to='ModFiles/%Y/%m/%d')
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateField(auto_now_add=True)
    changelogs = models.TextField()
    documentation = models.TextField()

    # comment = models.ForeignKey(Comment, on_delete=models.CASCADE, editable=False, blank=True, null = True)


    def __str__(self):
        return f' {self.mod} v.{self.version}'

    class Meta:
        unique_together = 'mod', 'version'


class Download(models.Model):
    mod_version = models.ForeignKey('ModVersion', on_delete=models.CASCADE)
    user = models.CharField(max_length=30)
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.mod_version

    class Meta:
        pass

mod/forms.py
import requests
from django import forms
from django.forms import inlineformset_factory, ModelForm

from .models import *




class ChoseGameForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = 'game',


class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class ModVersionCreationForm(forms.ModelForm):

    class Meta:
        model = ModVersion
        exclude = 'mod',


class ModCreationForm(forms.ModelForm):
    class Meta:
        model = Mod
        exclude = 'author',



#
# ModInlineFormSet = inlineformset_factory(Mod, ModVersion,
#                                          form=ModVersionInline,
#                                          extra=1,
#                                          can_delete=False,
#                                          fields='__all__')



# class RecipeForm(ModelForm):
#     error_css_class = 'error-field'
#     required_css_class = 'required-field'
#     #name = forms.CharField(help_text='This is your help! <a href="/contact">Contact us</a>')
#
#     # descriptions = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))
#     class Meta:
#         model = Mod
#         fields = ['name', 'description', 'directions']
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         # django-crispy-forms
#         for field in self.fields:
#             new_data = {
#                 "placeholder": f'Recipe {str(field)}',
#                 "class": 'form-control',
#                 # "hx-post": ".",
#                 # "hx-trigger": "keyup changed delay:500ms",
#                 # "hx-target": "#recipe-container",
#                 # "hx-swap": "outerHTML"
#             }
#             self.fields[str(field)].widget.attrs.update(
#                 new_data
#             )
#         # self.fields['name'].label = ''
#         # self.fields['name'].widget.attrs.update({'class': 'form-control-2'})
#         self.fields['description'].widget.attrs.update({'rows': '2'})
#         self.fields['directions'].widget.attrs.update({'rows': '4'})


# class RecipeIngredientForm(ModelForm):
#     class Meta:
#         model = ModVersion
#         fields = ['name', 'quantity', 'unit']

mod/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from .forms import *
from .utils import DataMixin


class AllGames(ListView):
    model = Game
    template_name = 'mod/all_games.html'
    context_object_name = 'games'


def chose_game(request):
    if request.method == 'POST':
        form = ChoseGameForm(request.POST)
        if form.is_valid():
            game_slug = form.cleaned_data['game'].slug
            return redirect(reverse('modif:add_mod', kwargs={'slug': game_slug}))
        return render(request, 'mod/chose_game.html', {'form': form, 'title': 'Chose a game'})
    form = ChoseGameForm()
    return render(request, 'mod/chose_game.html', {'form': form, 'title': 'Chose a game'})


class AllMods(DataMixin, ListView):
    model = Mod
    template_name = 'mod/all_mods.html'
    context_object_name = 'mods'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Главная страница")
        return {**context, **c_def}


class ModCategoriesForGame(DataMixin, ListView):
    model = Category
    template_name = 'mod/categories.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.filter(game__slug=self.kwargs['game_slug'])


class ModsByCategory(DataMixin, ListView):
    model = Mod
    context_object_name = 'mods'
    template_name = 'mod/mods_by_category.html'

    def get_queryset(self):
        return Mod.objects.filter(category__slug=self.kwargs['category_slug'])


class ModDetails(DetailView):
    model = Mod
    template_name = 'mod/get_mod.html'
    context_object_name = 'mod'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mod_versions'] = ModVersion.objects.filter(mod__slug=self.kwargs['slug'])
        return context


def add_modversion(request, slug):
    if request.method == 'POST':
        form = ModVersionCreationForm(request.POST, request.FILES)
        if form.is_valid():
            new_mod_version = form.save(commit=False)
            new_mod_version.mod = Mod.objects.get(slug=slug)
            new_mod_version.save()
            form.save()
            return redirect('modif:all_mods')
        return render(request, 'mod/add_modversion.html', {'form': form, 'title': 'Add new post'})
    form = ModVersionCreationForm()
    return render(request, 'mod/add_modversion.html', {'form': form, 'title': 'Add new post', 'slug': slug})


def add_mod(request, slug):
    if request.method == 'POST':
        form = ModCreationForm(request.POST, request.FILES)

        if form.is_valid():
            new_mod = form.save(commit=False)
            new_mod.save()
            form.save_m2m()
            return redirect(reverse('modif:add_modversion', kwargs={'slug': new_mod.slug}))

        return render(request, 'mod/add_mod.html', {'form': form, 'title': 'Add new post', 'slug': slug})
    form = ModCreationForm()
    form.fields['category'].queryset = Category.objects.filter(game__slug=slug)

    return render(request, 'mod/add_mod.html', {'form': form, 'title': 'Add new post', 'slug': slug})






# class CreateModView(CreateView):
#     model = Mod
#     template_name = 'mod/add_mod.html'
#     form_class = ModCreationForm
#     success_url = reverse_lazy('modif:add_modversion')
#
#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         print(' CLASS WORKS')
#         return super().form_valid(form)
#
#
# class CreateModVersionView(CreateView):
#     model = ModVersion
#     template_name = 'mod/add_modversion.html'
#     form_class = ModVersionCreationForm
#     success_url = reverse_lazy('modif:all_mods')

mod/templates/mod/add_mod.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Add new mod</h1>
<form  action="{% url 'modif:add_mod' slug=slug %}" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input  type="submit" value="Next stage">
</form>

</body>
</html>

mod/templates/mod/add_modversion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Add new mod version</h1>
<form  action="{% url 'modif:add_modversion' slug=slug%}" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input  type="submit" value="Submit">
</form>

</body>
</html>

mod/templates/mod/all_mods.html
{% extends 'mod/base.html' %}
{% block title %}Mods{% endblock%}


{% block content%}
<br>
<br>
{% for mod in mods %}
{{mod.name}}
<br>
{% endfor %}
{% endblock%}

mod/templates/mod/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
            {% block title %}{% endblock%}
    </title>
</head>

<body>
<a href="{% url 'modif:all_mods'  %}">Home</a>

{%for game in games%}
<a href="{{game.get_absolute_url}}">{{game.name}}</a>
{%endfor%}

 <a href="{% url 'modif:chose_game'  %}">Add mod</a>

{% block content%}
{% endblock%}
</body>
</html>

mod/templates/mod/categories.html
{% extends 'mod/base.html' %}

{% block title %}Categories{% endblock%}


{% block content%}

{% for category in categories %}

<a href="{{ category.get_absolute_url }}">{{category.name}}</a>

{% endfor %}


{% endblock%}

mod/templates/mod/chose_game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>chose game</h1>
<form  action="{% url 'modif:chose_game' %}" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input  type="submit" value="Next stage">
</form>

</body>
</html>

mod/templates/mod/create_mod.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create </title>
</head>
<body>

<form method="POST" enctype="multipart/form-data" action="{% url 'create_mod' %}">
    {%csrf_token%}
    {{f}}
    <div class="row">
        {% for f in form %}

        <div class="span3">{{f.label}} {{f}}
            {% if f.errors%}
            {%for v in f.errors %}
            <br><span style="color:red ;">{{v}} </span>
            {%endfor%}
            {%endif%}
        </div>
        {%endfor%}
    </div>

    <h2>modversion</h2>
    <table class="table-striped">
        <table>
            {%for f2 in inlines %}
            <tr id="{{f2.prefix}}-row">
                {% for i in f2%}
                <td>
                    {{i}} {%if i.errors%} <span style="color: :red;">{{i.errors}}</span>{%endif%}
                </td>
                {%endfor%}
            </tr>
            {%endfor%}
        </table>
    </table>
    {{inlines.management_form}}
    <input type="submit" class="btn btn_primary" value="Go">
</form>

</body>
</html>

mod/templates/mod/create_mod_version.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Add new mod version</h1>
<form  action="{% url 'modif:create_mod_version' slug=slug%}" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}
    <input  type="submit" value="Submit">
</form>

</body>
</html>

mod/templates/mod/get_mod.html
{% extends 'mod/base.html' %}
{% block title %}Mods{% endblock%}


{% block content%}
<br>
{{mod.name}}<br>

{%for modversion in mod_versions%}
<ul>
    <li>{{modversion.version}}</li>
<li><a href="{{  modversion.files.url }}">Файл</a></li>
    <li>{{modversion.created_at}}</li>
    <li>{{modversion.updated_at}}</li>
    <li>Changelogs: {{modversion.changelogs}}</li>
    <li>Documentation: {{modversion.documentation}}</li>

</ul>
{%endfor%}

{% endblock%}

mod/templates/mod/mods_by_category.html
{% extends 'mod/base.html' %}

{% block title %}Mods{% endblock%}


{% block content%}

{% for mod in mods %}

<a href="{{mod.get_absolute_url}} ">{{mod.name}}</a>

{% endfor %}


{% endblock%}